glossary <-
structure(list(Acronym = c("(C)BIP", "2007 Interim Guidelines", 
"2007 Interim Guidelines Final EIS", "3-State Agreement", "7/30", 
"AF", "Ag", "ALPWCD", "AMA", "AOP", "ARC", "ASU", "AWRA", "AWS", 
"AWWA", "Basin", "Basin States", "BCNM", "BLM", "BLWCD", "BMWCD", 
"BO", "BOR", "BRM", "BWCD", "C-BT", "CAP", "CBM", "CCWCD", "CDF", 
"CDPHE", "CFB", "CFOPS", "CFS", "CFWE", "CGWC", "CMIP", "Compact", 
"CRB", "CRBS", "CRC", "CRCA", "CRDSS", "CREA", "CRMMS", "CROS", 
"CRPAB", "CRRIM", "CRSC", "CRSM", "CRSP", "CRSPA", "CRSS", "CRSSPR-VIZ", 
"CRWCD", "CRWUA", "CSU", "CU", "CUP", "CWA", "CWC", "CWCB", "CWQCC", 
"CWQCC/D", "CWRPDA", "CWRRI", "DCP", "DCWRA", "desal", "DMDU", 
"DMI", "DNR", "DOI", "DougCo", "DSS", "DW", "DWR", "EA", "EC", 
"EDF", "EIA", "EIS", "EPA", "EPRP", "ERA", "ERWSD", "ESA", "ET", 
"FERC", "Flaming Gorge Unit", "FONSI", "FRICO", "ft", "GASP", 
"GCM", "GIS", "Glen Canyon Unit", "GMR", "GMUG", "GSF", "Gulf", 
"GVIC", "GVWUA", "GWh", "HCCA", "HUP", "ICPA", "ICS", "IG", "IGA", 
"IID", "IIJA", "IMAP", "IMC", "Interim Guidelines", "IRP", "ISM", 
"IWB", "KAF", "kafy", "LB", "Live Storage", "M&I", "MAF", "mafy", 
"MAWG", "MCID", "MCWA", "Mexico", "MOA", "MOEA", "MOU", "MPWCD", 
"MRM", "MSL", "MWD", "MWSI", "MX", "Navajo Unit", "NCWCD", "NEPA", 
"NFMA", "NISP", "NPDES", "NPS", "NRCS", "NWCCOG", "NWRA", "OMID", 
"OWC", "PBO", "PID", "Reclamation", "PRP", "PSOP", "PWSD", "QQ", 
"QSA", "RBWCD", "RCL", "RDBMS", "RFC", "RGWCD", "RGWUA", "RICD", 
"RIP", "RIP-RAP", "RMNP", "ROD", "RRA", "RRG", "RW", "RWPA", 
"RWPC", "SECWCD", "SEO", "SJCP", "SNWA", "SoCal", "SSI", "Study", 
"SUPERCAT", "SWCD", "SWSI", "SWWCD", "TABOR", "TAC", "TCWCD", 
"TDS", "TNC", "Trace", "TRCP", "TU", "UCRC", "UGRWCD", "UPCO", 
"USACE", "USBR", "USF", "USFWS", "USGS", "USSD", "UVWUA", "UWCD", 
"UYWCD", "WA", "WAPA", "Wayne N. Aspinall Unit", "WDWCD", "WESTCAS", 
"WRNF", "WSRA", "WSWC", "YDP", "YJWCD", "YRBP"), Definition = c("(Colorado) Basin Implementation Plan", 
"Record of Decision for Colorado River Interim Guidelines for Lower Basin Shortages and Coordinated Operations for Lake Powell and Lake Mead", 
"Colorado River Interim Guidelines for Lower Basin Shortages and Coordinated Operations for Lake Powell and Lake Mead Final Environmental Impact Statement", 
"State Agreement – Colorado/Nebraska/Wyoming for Platte River Endangered Species", 
"Seven States/30 Sovereign Tribal Nations in the Colorado River Basin", 
"Acre-foot, Acre-feet", "agricultural", "Animas-La Plata Water Conservancy District", 
"Active Management Area", "Annual Operating Plan (ref: Bureau of Reclamation Colorado River operations)", 
"Arizona Reconsultation Committee", "Arizona State University", 
"American Water Resources Association", "Amazon Web Services", 
"American Water Works Association", "Colorado River Basin", "Colorado River Basin States", 
"Black Canyon of the Gunnison National Monument", "U.S. Bureau of Land Management", 
"Bluestone Water Conservancy District", "Battlement Mesa Water Conservancy District", 
"Biological Opinion", "Bureau of Reclamation", "Big River Model", 
"Basalt Water Conservancy District", "Colorado-Big Thompson Project", 
"Central Arizona Project", "Coal Bed Methane", "Central Colorado Water Conservancy District", 
"Cumulative Density Function", "Colorado Department of Public Health and Environment", 
"Colorado Farm Bureau", "Coordinated Facilities Operations Study (ref: Fish Recovery Program)", 
"Cubic Feet Per Second", "Colorado Foundation for Water Education", 
"Colorado Ground Water Commission", "Coupled Model Intercomparison Project (Climate models from the WCRP (World Climate Research Program))", 
"Colorado River Compact", "Colorado River Basin", "Colorado River Basin Study", 
"Colorado River Collaborative", "Colorado River Cooperative Agreement", 
"Colorado River Decision Support System", "Colorado Rural Electric Association", 
"Colorado River Mid-term Modeling System", "Combined Reservoir Operations Study", 
"Colorado River Policy Advisory Board", "Colorado River Resilience Investment Model", 
"Colorado River Sustainability Campaign", "Colorado River Simulation Mode", 
"Colorado River Storage Project", "Colorado River Storage Project Act", 
"Colorado River Simulation System", "CRSS PlotR & Visualization", 
"Colorado River Water Conservation District", "Colorado River Water Users Association", 
"Colorado Springs Utilities", "Consumptive Use", "Central Utah Project", 
"Clean Water Act", "Colorado Water Congress", "Colorado Water Conservation Board", 
"Colorado Water Quality Control Committee", "Colorado Water Quality Control Commission/Division", 
"Colorado Water Resources & Power Development Authority", "Colorado Water Resources Research Institute", 
"Drought Contingency Plan", "Douglas County Water Resource Authority", 
"desalination", "Decision Making Under Deep Uncertainty", "Data Management Interface", 
"Department of Natural Resources (Colorado)", "U.S. Department of the Interior", 
"Douglas County Water Resources Authority Study", "Decision Support System", 
"Denver Water", "Division of Water Resources (Colorado/ aka: SEO)", 
"Environmental Assessment (ref: Colorado)", "extraordinary conservation", 
"Environmental Defense Fund", "U.S. Energy Information Administration", 
"Environmental Impact Statement", "Environmental Protection Agency", 
"Eagle Park Reservoir Project", "Eagle River Assembly", "Eagle River Water & Sanitation District", 
"Endangered Species Act", "Evapotranspiration", "Federal Energy Regulatory Commission", 
"Flaming Gorge Dam", "Finding of No Significant Impact (NEPA)", 
"Farmer’s Reservoir and Irrigation Company", "feet", "Groundwater Appropriators of the South Platte", 
"General Circulation Model", "Geographical Information System", 
"Glen Canyon Dam", "Green Mountain Reservoir", "Grand Mesa, Uncompahgre and Gunnison National Forests", 
"Groundwater Storage Facilities", "Gulf of California", "Grand Valley Irrigation Company", 
"Grand Valley Water Users Association", "gigawatt-hour", "High Country Citizen’s Alliance", 
"Historic Users Pool (refers to Green Mountain Reservoir)", "Interstate Compact Policy Analysis", 
"Intentionally Created Surplus", "Interim Guidelines", "Inter-Governmental Agreement", 
"Imperial Irrigation District (California)", "Infrastructure Investment and Jobs Act", 
"Information Management Annual Plan", "Information Management Committee", 
"2007 Interim Guidelines", "Integrated Resource Plan", "Index Sequential Method", 
"Interstate Water Bank", "thousand acre-feet", "thousand acre-feet per year", 
"The Lower Basin", "Live storage is the reservoir storage capacity excluding storage lower than the dead pool elevation.", 
"municipal and industrial", "Million Acrefeet", "million acre-feet per year", 
"Modeling and Analysis Working Group (in AZ)", "Mesa County Irrigation District", 
"Mesa County Water Association", "United Mexican States", "Memorandum of Agreement", 
"Multi-objective evolutionary algorithm (MOEA) is the main method to solve multi-objective optimization problem (MOP)", 
"Memorandum of Understanding", "Middle Park Water Conservancy District", 
"Multiple Run Management (Riverware)", "above mean sea level", 
"Metropolitan Water District of Southern California", "Metropolitan Water Supply Investigation", 
"Mexico", "Navajo Dam", "Northern Colorado Water Conservancy District (Northern Water)", 
"National Environmental Policy Act", "National Forest Management Act", 
"Northern Integrated Supply Project", "National Pollutant Discharges Elimination System", 
"National Park Service (Department of Interior)", "Natural Resources Conservation Service", 
"Northwest Colorado Council of Governments", "National Water Resources Association", 
"Orchard Mesa Irrigation District", "Office of Water Conservation (Colorado Water Conservation Board)", 
"Programmatic Biological Opinion", "Palisade Irrigation District", 
"Bureau of Reclamation", "Platte River Project", "Preferred Storage Options Plan", 
"Parker Water & Sanitation District", "Water Quantity and Quality Committee of Northwest Colorado Council of Governments", 
"Quantification Settlement Agreement", "Rio Blanco Water Conservancy District", 
"Rule command language (Riverware)", "Relational Database Management System", 
"Roaring Fork Conservancy", "Rio Grand Water Conservation District", 
"Rio Grande Water Users’ Association", "Recreational In-Channel Diversion", 
"Recovery Implementation Program", "Recovery Implementation Program – Recovery Action Plan", 
"Rocky Mountain National Park", "Record of Decision", "Reclamation Reform Act", 
"Renewable Resources Group", "Riverware", "Ruedi Water/Power Authority", 
"Redlands Water & Power Company", "Southeast Colorado Water Conservancy District", 
"State Engineer’s Office", "San Juan Chama Project", "Southern Nevada Water Authority", 
"Southern California", "self-served industrial", "Colorado River Basin Water Supply and Demand Study", 
"Super Colorado River Allocation Tabulation", "Silt Water Conservancy District", 
"Statewide Water Supply Initiative", "Southwestern Water Conservation District", 
"Taxpayer’s Bill of Rights", "Technical Advisory Committee", 
"Tri-county Water Conservancy District", "Total Dissolved Solids", 
"The Nature Conservancy", "Traces are individual time series datasets run through a model, usually in an ensemble.", 
"Teddy Roosevelt Conservation Partnership", "Trout Unlimited", 
"Upper Colorado River Commission", "Upper Gunnison River Water Conservancy District", 
"Upper Colorado River Basin Study", "U.S. Army Corps of Engineers", 
"United States Bureau of Reclamation", "Underground Storage Facilities", 
"United States Fish and Wildlife Service", "United States Geologic Survey", 
"United States Society on Dams", "Uncompahgre Valley Water Users Association", 
"Ute Water Conservancy District", "Upper Yampa Water Conservancy District", 
"Wilderness Act", "Western Area Power Authority", "Blue Mesa Dam, Crystal Dam, Morrow Point Dam", 
"West Divide Water Conservancy District", "Western Coalition of Arid States", 
"White River National Forest", "Wild & Scenic Rivers Act", "Western States Water Council", 
"Yuma Desalting Plant", "Yellow Jacket Water Conservancy District", 
"Yampa River Basin Partnership"), Notes = c(NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, "coalition of non-profits from both upper and lower basin", 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, "Policy construct that allows water users to conserve water or not request their water and get credits to their account for subsequent years", 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, "Season serves as a representative for the environmental groups", 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA), Link = c("https://www.colorado.gov/pacific/sites/default/files/CBIP-April-17-2015.pdf", 
NA, NA, NA, NA, "http://www.convertunits.com/info/acre+foot", 
NA, "http://www.waterinfo.org/about-wip/participating-entities/animas-la-plata-water-conservancy-district", 
NA, NA, "https://new.azwater.gov/arc", NA, "http://www.awra.org/", 
NA, "https://www.awwa.org/", NA, NA, "http://www.nps.gov/blca/index.htm", 
"https://www.blm.gov/", NA, NA, NA, NA, NA, "http://bwcd.org/", 
"http://www.northernwater.org/WaterProjects/C-BTProject.aspx", 
"http://www.cap-az.com/", "http://en.wikipedia.org/wiki/Coalbed_methane", 
"http://www.ccwcd.org/", NA, "https://www.colorado.gov/cdphe", 
"http://www.coloradofarmbureau.com/", "http://www.coloradoriverrecovery.org/", 
NA, "https://www.yourwatercolorado.org/", "http://water.state.co.us/cgwc", 
"https://www.wcrp-climate.org/wgcm-cmip/cmip-video", NA, NA, 
NA, NA, NA, "http://cdss.state.co.us/Pages/CDSSHome.aspx", "http://www.crea.coop/", 
"https://www.usbr.gov/lc/region/g4000/riverops/model-info.html", 
"http://www.fws.gov/mountain-prairie/wtr/coloriver.htm#CROI%20Plan", 
NA, NA, NA, NA, NA, "http://www.fws.gov/laws/lawsdigest/colobas.html", 
NA, NA, "https://www.coloradoriverdistrict.org/", "http://www.crwua.org/", 
"https://www.csu.org/Pages/default.aspx", NA, "http://www.cap-az.com/", 
"http://www.epa.gov/agriculture/lcwa.html", "http://www.cowatercongress.org/", 
"http://cwcb.state.co.us/Pages/CWCBHome.aspx", "https://www.colorado.gov/pacific/cdphe/wqcc", 
"https://www.colorado.gov/pacific/cdphe/wqcd", "http://www.cwrpda.com/", 
"http://www.cwi.colostate.edu/", NA, "http://www.dcwater.org/", 
NA, NA, NA, NA, "http://www.doi.gov/index.cfm", "http://www.dcwater.org/", 
"http://www.techopedia.com/definition/770/decision-support-system-dss", 
"http://www.denverwater.org/", "http://water.state.co.us/", "http://www.epa.gov/myenv/myenview2.html?minx=-111.64307&miny=36.82687&maxx=-99.44824&maxy=41.17865&ve=6,38.99854,-105.54781&pSearch=Colorado", 
NA, NA, NA, "http://www.epa.gov/compliance/nepa/eisdata.html", 
"http://www.epa.gov/", NA, NA, "http://www.erwsd.org/", NA, NA, 
"http://www.ferc.gov/", NA, "http://environment.fhwa.dot.gov/projdev/docufonsi.asp", 
"http://www.users.farmersres.com/", NA, NA, NA, NA, NA, "http://www.northernwater.org/WaterProjects/GreenMountainReservoir.aspx", 
"http://www.fs.usda.gov/gmug", NA, NA, NA, "http://www.irrigationprovidersgv.org/GVWUA.php", 
NA, "http://www.hccaonline.org/", NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, "https://www.americanrivers.org/river/lower-basin-colorado-river/", 
NA, NA, NA, NA, NA, "http://www.irrigationprovidersgv.org/MCID.php", 
"http://mesacountywater.org/", NA, NA, "Borg MOEA", NA, NA, NA, 
NA, "http://www.mwdh2o.com/", NA, NA, NA, "http://www.ncwcd.org/", 
"http://www.epa.gov/compliance/nepa/", "http://www.fs.fed.us/emc/nfma/index.htm", 
"http://www.northernwater.org/WaterProjects/NISP.aspx", "https://www.epa.gov/npdes", 
"http://www.nps.gov/", "http://www.nrcs.usda.gov/", "http://www.nwccog.org/", 
"http://www.nwra.org/", "http://www.irrigationprovidersgv.org/OMID.php", 
NA, NA, NA, NA, NA, NA, "http://www.pwsd.org/", "http://www.nwccog.org/index.php/programs/water-qualityquantity-committee/", 
"http://www.watereducation.org/aquapedia/quantification-settlement-agreement", 
NA, NA, NA, "http://www.roaringfork.org/", NA, NA, "http://cwcb.state.co.us/environment/recreational-in-channel-diversions/Pages/main.aspx", 
"http://www.coloradoriverrecovery.org/documents-publications/foundational-documents/recovery-action-plan.html", 
"http://www.coloradoriverrecovery.org/documents-publications/foundational-documents/recovery-action-plan.html", 
"http://www.nps.gov/romo/", NA, NA, NA, NA, "http://www.rwapa.org/", 
NA, "http://www.secwcd.org/", "http://water.state.co.us/", NA, 
NA, NA, NA, NA, NA, NA, "http://cwcb.state.co.us/public-information/publications/pages/studiesreports.aspx", 
"http://swwcd.org/", "http://www.colorado.gov/cs/Satellite/Treasury_v2/CBON/1251592160342", 
NA, "http://tricountywater.org/", NA, "http://nature.org/", NA, 
NA, "http://www.tu.org/index.asp", NA, "http://www.ugrwcd.org/", 
"http://www.usbr.gov/lc/region/programs/crbstudy.html", "http://www.usace.army.mil/", 
"http://www.usbr.gov/", NA, "http://www.fws.gov/", "http://www.usgs.gov/", 
"http://www.ussdams.org/", "http://www.waterhistory.org/histories/reclamation/uncompahgre/", 
"http://www.utewater.org/", "http://www.upperyampawater.com/", 
"http://www.wilderness.net/NWPS/legisact", "http://www.wapa.gov/", 
NA, "http://www.wdwcd.org/", "http://www.westcas.org/", "http://www.fs.fed.us/r2/whiteriver/", 
"http://www.nps.gov/rivers/wsract.html", "http://www.westernstateswater.org/", 
NA, NA, "http://www.yampavalleypartners.com/yampa_river.html"
), `tolower(Acronym)` = c("(c)bip", "2007 interim guidelines", 
"2007 interim guidelines final eis", "3-state agreement", "7/30", 
"af", "ag", "alpwcd", "ama", "aop", "arc", "asu", "awra", "aws", 
"awwa", "basin", "basin states", "bcnm", "blm", "blwcd", "bmwcd", 
"bo", "bor", "brm", "bwcd", "c-bt", "cap", "cbm", "ccwcd", "cdf", 
"cdphe", "cfb", "cfops", "cfs", "cfwe", "cgwc", "cmip", "compact", 
"crb", "crbs", "crc", "crca", "crdss", "crea", "crmms", "cros", 
"crpab", "crrim", "crsc", "crsm", "crsp", "crspa", "crss", "crsspr-viz", 
"crwcd", "crwua", "csu", "cu", "cup", "cwa", "cwc", "cwcb", "cwqcc", 
"cwqcc/d", "cwrpda", "cwrri", "dcp", "dcwra", "desal", "dmdu", 
"dmi", "dnr", "doi", "dougco", "dss", "dw", "dwr", "ea", "ec", 
"edf", "eia", "eis", "epa", "eprp", "era", "erwsd", "esa", "et", 
"ferc", "flaming gorge unit", "fonsi", "frico", "ft", "gasp", 
"gcm", "gis", "glen canyon unit", "gmr", "gmug", "gsf", "gulf", 
"gvic", "gvwua", "gwh", "hcca", "hup", "icpa", "ics", "ig", "iga", 
"iid", "iija", "imap", "imc", "interim guidelines", "irp", "ism", 
"iwb", "kaf", "kafy", "lb", "live storage", "m&i", "maf", "mafy", 
"mawg", "mcid", "mcwa", "mexico", "moa", "moea", "mou", "mpwcd", 
"mrm", "msl", "mwd", "mwsi", "mx", "navajo unit", "ncwcd", "nepa", 
"nfma", "nisp", "npdes", "nps", "nrcs", "nwccog", "nwra", "omid", 
"owc", "pbo", "pid", "reclamation", "prp", "psop", "pwsd", "qq", 
"qsa", "rbwcd", "rcl", "rdbms", "rfc", "rgwcd", "rgwua", "ricd", 
"rip", "rip-rap", "rmnp", "rod", "rra", "rrg", "rw", "rwpa", 
"rwpc", "secwcd", "seo", "sjcp", "snwa", "socal", "ssi", "study", 
"supercat", "swcd", "swsi", "swwcd", "tabor", "tac", "tcwcd", 
"tds", "tnc", "trace", "trcp", "tu", "ucrc", "ugrwcd", "upco", 
"usace", "usbr", "usf", "usfws", "usgs", "ussd", "uvwua", "uwcd", 
"uywcd", "wa", "wapa", "wayne n. aspinall unit", "wdwcd", "westcas", 
"wrnf", "wsra", "wswc", "ydp", "yjwcd", "yrbp")), row.names = c(NA, 
-216L), class = c("tbl_df", "tbl", "data.frame"))
