col_1 <-
function (...) 
shiny::column(1L, ...)
col_2 <-
function (...) 
shiny::column(2L, ...)
col_3 <-
function (...) 
shiny::column(3L, ...)
col_4 <-
function (...) 
shiny::column(4L, ...)
col_5 <-
function (...) 
shiny::column(5L, ...)
col_6 <-
function (...) 
shiny::column(6L, ...)
col_7 <-
function (...) 
shiny::column(7L, ...)
col_8 <-
function (...) 
shiny::column(8L, ...)
col_9 <-
function (...) 
shiny::column(9L, ...)
col_10 <-
function (...) 
shiny::column(10L, ...)
col_11 <-
function (...) 
shiny::column(11L, ...)
col_12 <-
function (...) 
shiny::column(12L, ...)
